[package]
name    = "svc-pricing"
version = "0.2.0-develop.1"
edition = "2021"            # Allowed values are 2015, 2018, 2021
# Rust Editions: https://doc.rust-lang.org/edition-guide/index.html

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-husky  = "1"
prost        = "0.11.0"
prost-types  = "0.11.1"
tokio        = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tonic        = "0.8.2"
tonic-health = "0.7.1"

[dev-dependencies.cargo-husky]
default-features = false          # Disable features which are enabled by default
features         = ["user-hooks"]
version          = "1"

[build-dependencies]
tonic-build = "0.8"
